### ISSUE TITLE
Issues with training 

### ISSUE THREAD

**Issue by DebaoHuang** [cvg/GeoCalib#1]
Hi,

Thanks for the amazing work! I was trying to train the model based on the instruction you provided, but I met the following problems:
        
(geocalib) (base) huang.3918@ceg-cnc197069d:/local/scratch1/degbo/GeoCalib$ python -m siclib.train geocalib-pinhole-openpano --conf geocalib
[09/13/2024 18:30:31 siclib INFO] Starting experiment geocalib-pinhole-openpano
Traceback (most recent call last):
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/local/scratch1/degbo/GeoCalib/siclib/train.py", line 728, in <module>
    conf = compose(config_name=args.conf, overrides=args.dotlist)
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/compose.py", line 38, in compose
    cfg = gh.hydra.compose_config(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 745, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 715, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 457, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 573, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 520, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 488, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/huang.3918/anaconda3/envs/geocalib/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'geocalib': Could not find 'data/openpano

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///local/scratch1/degbo/GeoCalib/siclib/configs
        provider=schema, path=structured://`
        
 It seems not able to find the training data under the path GeoCalib/siclib/configs. Could you please check if there is any problem with the code or configuration files? Thank you very much.

**Comment by veichta** [comment]
Hey, thank you for the pointing this out! The configs for the training data were missing. I've added them to the repo now. If you want to retrain our model, make sure to follow the instructions in the readme to create the openpano dataset under `data/openpano/openpano`.
